### ISSUE TITLE
Observation outside expected value range

### ISSUE THREAD

**Issue by drozzy** [CLEANit/heatenginegym#18]
Found an observation that falls outside the spec:
```
ValueError: ('Observation outside expected value range', Box(4,), 
array([5.00000000e+02, 8.00000000e-04, 4.64936388e-01, 1.96508428e-01]))
```

I know this is a PITA but the distributed framework we use makes assert checks on this and fails if it finds one that doesn't fit within the specific observation space.

**Comment by beelerchris** [comment]
The observation space is:
`env.observation_space.low`
`array([3.e+02, 2.e-04, 0.e+00, 0.e+00], dtype=float32)`
`env.observation_space.high`
`array([5.000000e+02, 1.000000e-03, 7.824496e-01, 5.129798e-01],
      dtype=float32)`
Which the observation you have gotten this error with is not above or below the specified space. Is it possible that the code you are using checks if the observation is less than env.observation_space.high but not equal to?

**Comment by drozzy** [comment]
`[5.00000000e+02, 8.00000000e-04, 4.64936388e-01, 1.96508428e-01]`

All they do is call `obs_space.contains(observation)`.
So they are using open-gym code.

**Comment by beelerchris** [comment]
I have modified the observation space to be 1e-6 below the true min and above the true max. Let me know if this solves the issue after the next PR goes through
